services:
  - type: web
    name: stock-analyzer-main
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
